In [6]:
import pymysql
import config  # Importa el archivo de configuración
import queries  # Importa el archivo de consultas SQL

# Conexión a la base de datos MariaDB
conexion = pymysql.connect(
    host=config.DB_HOST,       # Usando las credenciales de config.py
    user=config.DB_USER,
    password=config.DB_PASSWORD,
    database=config.DB_NAME
)

# Ejecutar la consulta desde queries.py
query = queries.QUERY_qx

with conexion.cursor() as cursor:
    cursor.execute(query)
    result = cursor.fetchall()

# Display the result
for row in result:
    print(row)

('Broncoscopia fibroóptica', 'D', '3322', 275)
('Otra broncoscopia', 'D', '3323', 162)
('Drenaje de cavidad pleural por toracoscopía', 'Q', '3406', 135)
('Otra septoplastia', 'Q', '2188', 126)
('Laringoscopia y otra traqueoscopia', 'D', '3142', 122)
('Biopsia pleural por toracoscopía', 'D', '3420', 99)
('Biopsia de pulmón por toracoscopía', 'D', '3320', 92)
('Otra rinoplastia', 'Q', '2187', 82)
('Toracotomía exploratoria', 'Q', '3402', 77)
('Toracoscopía transpleural', 'D', '3421', 66)
('Traqueostomía temporal', None, '311', 63)
('Decorticación de pulmón por toracoscopía', 'Q', '3452', 63)
('Lobectomía de pulmón', None, '324', 41)
('Desbridamiento excisional de herida, infección o quemadura', 'Q', '8622', 40)
('Otras operaciones sobre laringe', 'Q', '3198', 36)
('Lobectomía de pulmón por toracoscopía', 'Q', '3241', 36)
('Desbridamiento no excisional de herida, infección o quemadura', 'Q', '8628', 35)
('Amigdalectomía sin adenoidectomía', None, '282', 35)
('Cateterismo venoso, no clasificado bajo otro concepto', 'T', '3893', 35)
('excisión o resección de lesión o tejido de laringe', None, '300', 34)
('Incisión de cuello', 'Q', '6995', 33)
('Excisión de lesión o tejido pulmonar por toracoscopía', 'Q', '3220', 32)
('Otras operaciones sobre tráquea', 'Q', '3199', 30)
('Procedimiento toracoscópico asistido por robótica', 'Q', '00A5', 29)
('Implantación o sustitución de prótesis coclear no especificado de otra forma (implante coclear)', 'Q', '2096', 27)
('Otra traqueostomía permanente', 'Q', '3129', 27)
('Otra lobectomía de pulmón', 'Q', '3249', 24)
('Operaciones sobre senos nasales (paranasales)', None, '22', 22)
('Curación de herida', 'T', '00F9', 22)
('Resección segmentaría de pulmón por toracoscopía', 'Q', '3230', 21)
('Operaciones sobre la nariz', None, '21', 21)
('Decorticación de pulmón', 'Q', '3451', 21)
('Operaciones sobre la pared torácica, pleura, mediastino y diafragma', None, '34', 19)
('Otra timpanoplastia', None, '195', 19)
('Otras operaciones sobre laringe y tráquea', None, '31', 19)
('Broncoscopia a través de estoma artificial', 'D', '3321', 19)
('Laparotomía exploradora', 'Q', '5411', 18)
('Operaciones de reparación y plástica sobre tráquea', None, '317', 18)
('Amigdalectomía con adenoidectomía', None, '283', 17)
('Gastrostomía', None, '431', 15)
('Resección submucosa del tabique nasal (septoplastias)', None, '215', 15)
('Traqueostomía temporal', 'Q', '311X', 14)
('Resección segmentaria de pulmón', None, '323', 14)
('Otra resección segmentaría y la no especificada de pulmón', 'Q', '3239', 12)
('Plicatura de diafragma', 'Q', '5381', 11)
('Procedimientos asistidos por robótica', '', '00A', 10)
('Otra incisión con drenaje de piel y tejido subcutáneo', 'Q', '8604', 10)
('Otra biopsia pleural', 'D', '3424', 9)
('Biopsia cerrada [endoscópica] de laringe', 'D', '3143', 9)
('COLOCACIÓN DE BOMBA DE VACÍO (VAC)', 'T', '935A', 8)
('Otra operación sobre la nariz', 'Q', '2199', 8)
('Otras operaciones  sobres senos nasales (paranasales)', 'Q', '229X', 8)
('Broncografía endotraqueal', 'D', '8731', 8)
('Amigdalectomía con adenoidectomía', 'Q', '283X', 8)
('Otras operaciones de reconstrucción y plástica sobre tráquea', 'Q', '3179', 8)
('Tiroidectomía total', None, '64', 7)
('Revisión  de traqueostomía', 'Q', '3174', 7)
('Otra incisión de laringe o tráquea', 'Q', '3121', 7)
('Biopsia de pericardio', 'D', '3724', 7)
('Biopsia cerrada [endoscópica] [punción con aguja] de seno nasal', 'D', '2211', 7)
('Fractura de cornetes', 'Q', '2162', 6)
('Excisión de hueso para injerto, escápula, clavícula y tórax [costillas y esternón]', 'Q', '7771', 6)
('Neumonectomía [Pneumonectomía]', None, '325', 6)
('Biopsia abierta de mediastino', 'D', '3426', 6)
('Laparoscopia', 'D', '5421', 6)
('Sustitución de tubo de traqueostomía', 'T', '9723', 6)
('Otros procedimientos diagnósticos sobre tráquea', 'D', '3149', 6)
('Otros procedimientos diagnósticos sobre mediastino', 'D', '3429', 6)
('Rinoplastia de aumento', 'Q', '2185', 5)
('Timectomía, no especificada de otra manera', 'Q', '780', 5)
('Toracocentesis', 'Q', '3491', 5)
('Inserción de tubo endotraqueal', 'T', '9604', 5)
('Reapertura a través de toracotomía reciente', 'Q', '3403', 5)
('Miringotomía con inserción de tubo', 'Q', '2001', 5)
('Otra biopsia cervical', 'D', '6712', 5)
('Cierre de otra fístula de tráquea', 'Q', '3173', 5)
('Biopsia de estructura linfática', 'D', '4011', 5)
('Otras operaciones sobre senos nasales (paranasales)', None, '229', 4)
('Ablación de lesión o tejido de pulmón por toracoscopía', 'Q', '3225', 4)
('Drenaje de absceso dentario', 'T', '00G1', 4)
('ASPIRADO TRAQUEAL, ASPIRADO NASOFARÍNGEO O LAVADO NASAL PARA COVID-19', 'D', '00J0', 4)
('Drenaje de cara y suelo de la boca', 'Q', '270X', 4)
('Biopsia cerrada de pulmón por endocopía', 'D', '3327', 4)
('Examen microscópico de muestra de tráquea, bronquio, pleura, pulmón y de otra muestra torácica de y de otra muestra  torásica y de esputos. Otro examen microscópico', 'D', '9049', 4)
('Adenoidectomía sin amigdalectomía', None, '286', 4)
('Diálisis peritoneal', 'D', '5498', 4)
('Procedimiento laparoscópico asistido por robótica', 'Q', '00A2', 4)
('Revisión de rinoplastia (rinoplastia secundaria)', 'Q', '2184', 4)
('Biopsia de nariz', 'D', '2122', 4)
('Otras operaciones sobre laringe y tráquea', None, '319', 4)
('Fistulización traqueoesofágica', 'Q', '3195', 4)
('Cierre de fístula externa de tráquea', 'Q', '3172', 4)
('Otra operación sobre corazón y pericardio', 'Q', '3799', 4)
('TIROIDECTOMÍA TOTAL', None, '064', 4)
('Injerto de hueso, sscápula, clavícula y tórax [costillas y esternón]', 'Q', '7801', 4)
('CORDOTOMÍA', None, '032', 4)
('Cateterismo arterial', 'T', '3891', 4)
('Excisión local o destrucción de lesión o tejido de tráquea', 'Q', '315X', 4)
('Excisión o destrucción de lesión o tejido de mediastino', None, '343', 3)
('Control de hemorragia después de amigdalectomía y adenoidectomía', None, '287', 3)
('Otra reparación de hernia', 'Q', '539X', 3)
('Excisión de lesión maxilar de origen dentario', None, '244', 3)
('Procedimiento abierto asistido por robótica', 'Q', '00A1', 3)
('OPERACIONES SOBRE EL OÍDO (18 - 20)', None, '00', 3)
('Reconstrucción del pabellón del oído', 'Q', '1871', 3)
('Operaciones sobre glándulas y conductos salivales', None, '26', 3)
('Laringectomía total', None, '303', 3)
('Otra gastrostomía', 'Q', '4319', 3)
('Drenaje de cara y suelo de la boca', None, '270', 3)
('Biopsia abierta de la lengua', 'D', '2502', 3)
('Extracción de drenaje mediastínico', 'T', '9742', 3)
('Extirpación de ganglio linfático cervical profundo', 'Q', '4021', 3)
('Incisión de pared torácica y pleural', None, '340', 3)
('Colecistectomía', None, '512', 3)
('Extirpación radical de ganglios linfáticos cervicales', None, '404', 3)
('Procedimientos diagnósticos sobre pared torácica, pleura, mediastino y diafragma', None, '342', 3)
('Laparotomía', None, '541', 3)
('Cordectomía', 'Q', '3022', 3)
('TIMECTOMÍA', None, '078', 3)
('Biopsia cerrada de estómago (endoscópica)', 'D', '4414', 3)
('Fasciotomía', 'Q', '8314', 3)
('Extracción de tubo de toracotomía o de drenaje de la cavidad pleural', 'T', '9741', 3)
('Reparación de hernia diafragmática con acceso torácico, no especificada de otra manera', 'Q', '5380', 3)
('Biopsia abierta de pulmón', 'D', '3328', 3)
('Otra incisión de pleura', 'Q', '3409', 3)
('Amigdalectomía sin adenoidectomía', 'Q', '282X', 3)
('Mastoidectomía radical', 'Q', '2042', 3)
('Neumonectomía  [pneumonectomía] por toracoscopía', 'Q', '3250', 3)
('Cierre de fístula bronquial', 'Q', '3342', 3)
('Biopsia de piel y tejido subcutáneo', 'D', '8611', 3)
('Mastoidectomía', None, '204', 2)
('Excisión de lesión de glándula salival', None, '262', 2)
('Retirada de suturas de cabeza y cuello (Retirada de puntos)', 'T', '9738', 2)
('Reparación de deformidad de pectus', 'Q', '3474', 2)
('Otros procedimientos diagnósticos sobre senos nasales (maxilares)', 'D', '2219', 2)
('Otros procedimientos diagnósticos sobre la pared torácica, pleura y diafragma', 'D', '3428', 2)
('Biopsia abierta de nervio o ganglio craneal o periférico', 'D', '412', 2)
('Pericardiotomía', 'Q', '3712', 2)
('Sialoadenectomía total', 'Q', '2632', 2)
('Otras operaciones sobre glándula o conducto salival', None, '269', 2)
('Resección submucosa del tabique nasal (septoplastias)', 'Q', '215X', 2)
('Excisión de laringe', None, '30', 2)
('Cierre de fístula de seno maxilar', 'Q', '2271', 2)
('Trasplante de pulmón', None, '335', 2)
('Cierre de otra fístula de faringe', 'Q', '2953', 2)
('Operaciones en diafragma', None, '348', 2)
('Otra inmovilización, presión y cuidado de herida', None, '935', 2)
('Otra excisión de lesión de glándula salival', 'Q', '2629', 2)
('Revisión de mastoidectomía', 'Q', '2092', 2)
('Otra punción de vena', 'T', '3899', 2)
('Otras operaciones sobre la nariz', None, '219', 2)
('Miringotomía', None, '200', 2)
('Limpieza de traqueostomía', 'T', '9655', 2)
('Antrotomía maxilar externa', None, '223', 2)
('Otra reparación sobre pared torácica', 'Q', '3479', 2)
('Incisión de piel y tejido subcutáneo', None, '860', 2)
('LOBECTOMÍA TIROIDEA UNILATERAL', None, '062', 2)
('Dilatación bronquial', 'Q', '3391', 2)
('Extracción de tubo de traqueostomía', 'T', '9737', 2)
('Incisión de pared torácica', 'Q', '3401', 2)
('Extracción de otro diente', 'Q', '2309', 2)
('Otra incisión de laringe o tráquea', 'Q', '313X', 2)
('Otro lavado de bronquio y tráquea', 'T', '9656', 2)
('Otros procedimientos no quirúrgicos', None, '99', 2)
('Angiocardiografía de las venas cavas', 'D', '8851', 2)
('Extirpación de ganglio linfático inguinal', 'Q', '4024', 2)
('Pericardiectomía', 'Q', '3731', 2)
('Reparación de blefaroptosis por otras técnicas', 'Q', '836', 2)
('Incisión y drenaje de amígdala y estructuras periamigdalinas', 'Q', '280X', 2)
('Excisión de lesión maxilar de origen dentario', 'Q', '244X', 2)
('Biopsia abierta de laringe o tráquea', 'D', '3145', 2)
('Biopsia de pared torácica', 'D', '3423', 2)
('Extracción de diente con fórceps', None, '230', 2)
('Otra excisión de pulmón', None, '329', 2)
('Excisión de lesión de otro tejido blando', 'Q', '8339', 2)
('Examen microscópico de muestra de tráquea, bronquio, pleura, pulmón y de otra muestra torácica y de otra muestra  torásica y de esputos. Toxicología', 'D', '9045', 2)
('Examen microscópico de muestra de oido, nariz, garganta y laringe. Otro examen microscópico', 'D', '9039', 2)
('Pleurectomía', None, '345', 2)
('Excisión de hueso para injerto', None, '777', 2)
('Otra cirugía ortognática sobre mandíbula', 'Q', '7664', 2)
('Otras operaciones sobre corazón y pericardio', None, '379', 2)
('Sustitución de catéter de herida', 'T', '9715', 2)
('Otra herniorrafia umbilical abierta', 'Q', '5349', 2)
('Reparación de laringe', None, '316', 2)
('Amputación de miembro inferior', None, '841', 2)
('Otra reparación u operaciones plásticas en el hueso, escápula, clavícula y tórax [costillas y esternón]', 'Q', '7841', 1)
('EXTIRPACIÓN DE LESIÓN DE TIROIDES', 'Q', '0631', 1)
('Reparación abierta y otra reparación de otra hernia de la pared abdominal anterior con injerto o prótesis', 'Q', '5369', 1)
('Otros excisión de pleura', 'Q', '3459', 1)
('Otras operaciones y las no especificadas del timo por toracoscopia', 'Q', '798', 1)
('Biopsia de tejido blando', 'D', '8321', 1)
('Reparación abierta y otra reparación bilateral de hernia inguinal indirecta con injerto o prótesis', 'Q', '5315', 1)
('Otra mastoidectomía', 'Q', '2049', 1)
('Otra reparación de esófago', 'Q', '4289', 1)
('Reparación laparoscópica de hernia diafragmática, con abordaje torácico', 'Q', '5383', 1)
('Otras operaciones de reparación y operaciones plásticas de la nariz', 'Q', '2189', 1)
('Lisis de adherencias de tráquea o laringe', 'Q', '3192', 1)
('Retiro de catéter(es) de cavidad o tejido craneal', 'Q', '127', 1)
('Osteotomía en cuña escápula, clavícula y tórax [costillas y esternón]', 'Q', '7721', 1)
('Otra reparación de hueso facial y cirugía ortognática', None, '766', 1)
('Excisión o destrucción de lesión o tejido de mediastino', 'Q', '343X', 1)
('Otra sinusectomía nasal', None, '226', 1)
('Otra incisión del área tiroidea', 'Q', '609', 1)
('Intubación e irrigación no quirúrgicas', None, '96', 1)
('OPERACIONES SOBRE LAS GLÁNDULAS TIROIDES Y PARATIROIDES', None, '06', 1)
('Otras operaciones sobre la cavidad oral', 'Q', '2799', 1)
('Otra excisión de lesión o tejido de labio', 'Q', '2743', 1)
('EXCISIÓN DE LESIÓN DE GLÁNDULA SUPRARRENAL', 'Q', '0721', 1)
('Otra laparotomía', 'Q', '5419', 1)
('Plicatura de bulla enfisematosa', 'Q', '3221', 1)
('Extracción sin incisión de cuerpo extraño intraluminal de tráquea y bronquio', 'T', '9815', 1)
('Timpanoplastia tipo III', 'Q', '1953', 1)
('Colectomía intrabdominal total abierta', 'Q', '4582', 1)
('Reparación laparoscópica de hernia inguinal directa con injerto o prótesis', 'Q', '530A', 1)
('Esofagogastroduodenoscopía [EGD] con biopsia cerrada', 'D', '4516', 1)
('Extirpación radical de ganglios linfáticos, no especificada de otra manera', 'Q', '4050', 1)
('Excisión local o extirpación de otra lesión de nariz', 'Q', '2132', 1)
('Anastomosis de intestino grueso a intestino grueso', 'Q', '4594', 1)
('Gastrotomía', None, '430', 1)
('Osteoplastia [osteotomía] segmentaria de maxilar', 'Q', '7665', 1)
('Inserción de catéter intercostal para drenaje', 'Q', '3404', 1)
('Punción de pulmón', 'Q', '3393', 1)
('Mastoidectomía simple', 'Q', '2041', 1)
('Reconstrucción de conducto auditivo externo', 'Q', '186X', 1)
('Operaciones sobre el cuerpo carotídeo, seno carotideo y otros cuerpos vasculares', 'Q', '398X', 1)
('EXTIRPACIÓN PARCIAL DEL TIMO POR TORACOSCOPÍA', 'Q', '0783', 1)
('Ablación abierta de lesión o tejido de hígado', 'Q', '5023', 1)
('Operaciones sobre piel y tejido subcutáneo', None, '86', 1)
('Otra excisión o destrucción de lesión o tejido de la laringe', 'Q', '3009', 1)
('Amputación de dedo de pie', 'Q', '8411', 1)
('Incisión de mastoides', 'Q', '2021', 1)
('Otra esofagoscopía', 'D', '4223', 1)
('Cierre de fístula de laringe', 'Q', '3162', 1)
('Cateterismo venoso para diálisis renal', 'D', '3895', 1)
('Reconstrucción de tráquea y construcción de laringe artificial', 'Q', '3175', 1)
('Reconstrucción total de mama,Colgajo SIEA libre (con arteria epigástrica superficial inferior)', 'Q', '8575', 1)
('Endarterectomía, vasos de miembros superiores', 'Q', '3813', 1)
('Extracción de otro dispositivo terapéutico de cabeza y cuello', 'T', '9739', 1)
('Otra reparación del oído medio', 'Q', '199X', 1)
('Excisión local o extirpación de lesión intranasal', 'Q', '2131', 1)
('Colostomía', None, '461', 1)
('Marsupialización de quiste cervical', 'Q', '6731', 1)
('Otra reparación de aneurisma', 'Q', '3952', 1)
('Extracción de cuerpo extraño, no especificado de otra manera', 'T', '9820', 1)
('PROCEDIMIENTO SOBRE BIFURCACIÓN VASCULAR', 'Q', '0044', 1)
('Incisión del oído externo', 'Q', '1802', 1)
('BIOPSIA DE GLÁNDULA PARATIROIDES', 'D', '0613', 1)
('Incisión de absceso perianal', 'Q', '4901', 1)
('Timpanoplastia tipo II', 'Q', '1952', 1)
('Secuestrectomía de hueso facial', 'Q', '7601', 1)
('Extracción de otro dispositivo de abdomen', 'T', '9786', 1)
('Otra sinusotomía nasal', None, '225', 1)
('Otra reparación del oído medio', None, '199', 1)
('Otros procedimientos diagnósticos sobre corazón y pericardio', 'D', '3729', 1)
('Otras operaciones sobre hígado', None, '509', 1)
('Otra oclusión quirúrgica de vasos, sitio no especificado', 'Q', '3880', 1)
('Esplenectomía total', 'Q', '415X', 1)
('Otra inmovilización, presión y cuidado de herida', 'T', '9359', 1)
('Excisión local o extirpación de lesión de la pirámide nasal', None, '213', 1)
('Extracción de tapón nasal', 'T', '9732', 1)
('Excisión local o destrucción de lesión o tejido pulmonar', None, '322', 1)
('Otras operaciones de reparación y plástica sobre bronquio', 'Q', '3348', 1)
('Otra excisión de tejido blando', 'Q', '8349', 1)
('Procedimientos diagnósticos sobre hueso, no clasificados en otra parte escápula, clavícula y tórax [costillas y esternón]', 'D', '7881', 1)
('Excisión local de lesión o tejido de hueso escápula, clavícula y tórax [costillas y esternón]', 'Q', '7761', 1)
('OTRA TIROIDECTOMÍA PARCIAL', None, '063', 1)
('Fusión dorsal y dorsolumbar, técnica posterior', 'Q', '8105', 1)
('Colecistectomía laparoscópica', 'Q', '5123', 1)
('Exéresis o excisión ósea total, escápula, clavícula y tórax [costillas y esternón]', 'Q', '7791', 1)
('Extracción no quirúrgica de dispositivo terapéutico de cabeza y cuello', None, '973', 1)
('Otra estapedectomía', 'Q', '1919', 1)
('Examen microscópico de muestra de oido, nariz, garganta y laringe.', None, '903', 1)
('Control de epistaxis por cauterización (y taponamiento)', 'Q', '2103', 1)
('División de cápsula articular, ligamento o cartílago. Sitio no especificado', 'Q', '8040', 1)
('TIMECTOMÍA, NO ESPECIFICADA DE OTRA MANERA', 'Q', '0780', 1)
('Excisión de fístula preauricular', 'Q', '1821', 1)
('Lavado peritoneal', 'D', '5425', 1)
('Reparación de fractura laríngea', 'Q', '3164', 1)
('Excisión o resección de lesión o tejido de faringe', None, '293', 1)
('Revisión de timpanoplastia', None, '196', 1)
('OTRAS OPERACIONES SOBRE GLÁNDULAS, NERVIOS, Y VASOS SUPRARRENALES', None, '074', 1)
('Cardiotomía y pericardiotomía', None, '371', 1)
('Otras operaciones sobre glándulas tiroides', 'Q', '698', 1)
('Endarterectomía, arterias de miembros inferiores', 'Q', '3818', 1)
('Inserción de vía aérea orofaríngea', 'T', '9602', 1)
('Otra reparación endovascular (de aneurisma) de otros vasos', 'Q', '3979', 1)
('Escarificación de pleura', None, '346', 1)
('Amputación a través de húmero', 'Q', '8407', 1)
('Control de epistaxis por excisión de las mucosas nasales e injertos de piel en el tabique y la pared nasal lateral', 'Q', '2107', 1)
('TIROIDECTOMÍA RETROESTERNAL TOTAL', 'Q', '0652', 1)
('Esplenectomía total', None, '415', 1)
('Otra colecistostomía', 'Q', '5103', 1)
('Extracción de otro dispositivo de tórax', 'T', '9749', 1)
('Otra incisión de laringe o tráquea', None, '313', 1)
('Colangiografía intraoperatoria', 'D', '8753', 1)
('Angioplastía o aterectomía de otro(s) vaso(s) no coronario(s)', 'Q', '3950', 1)
('Reparación de hernia diafragmática, acceso torácico', None, '538', 1)
('Otra división de hueso escápula, clavícula y tórax [costillas y esternón]', 'Q', '7731', 1)
('Otra reparación de hernia incisional (eventración) con injerto o prótesis', 'Q', '5361', 1)
('INSERCIÓN DE CATÉTER(ES) EN CAVIDAD O TEJIDO CRANEAL', 'Q', '0126', 1)
('Oxigenación extracorpórea de membrana (OECM)', 'Q', '3965', 1)
('Adenoidectomía sin amigdalectomía', 'Q', '286X', 1)
('Excisión de quiste o vestigio de hendidura branquial', None, '292', 1)
('Examen microscópico de muestra de tráquea, bronquio, pleura, pulmón y de otra muestra torácica y de otra muestra torásica y de esputos', None, '904', 1)
('Cierre de esofagostomía', 'Q', '4283', 1)
('Biopsia cerrada [endoscópica] de tráquea', 'D', '3144', 1)
('Otra endoscopía de intestino delgado', 'D', '4513', 1)
('Biopsia abierta de seno nasal', 'D', '2212', 1)
('Pericardiocentesis', None, '370', 1)
('Otra reparación de orificio cervical interno', 'Q', '6759', 1)
('Operaciones sobre el riñón', None, '55', 1)
('Inyección en laringe', None, '310', 1)
('Colecistectomía', 'Q', '5122', 1)
('Apendicectomía laparoscópica', 'Q', '4701', 1)
('Otra incisión de tejido blando', 'Q', '8309', 1)
('Antrotomía intranasal', None, '222', 1)
('OPERACIONES SOBRE LA NARIZ, BOCA Y FARINGE (21 - 29)', None, '0', 1)
('Incisión de mediastino', 'Q', '341X', 1)
('Otra operación sobre tórax', 'Q', '3499', 1)
('Otra extracción no quirúrgica de dispositivo terapéutico', None, '978', 1)
('Amputación a través de pie', 'Q', '8412', 1)
('Fusión lumbar y lumbosacra, técnica posterior', 'Q', '8108', 1)
('Marsupialización de quiste laríngeo', 'Q', '3001', 1)
('Otra excisión local o destrucción de lesión o tejido pulmonar', 'Q', '3229', 1)
('Otros procedimientos diagnósticos sobre glándulas y conductos salivales', 'D', '2619', 1)
('Reparación de labio fisurado', 'Q', '2754', 1)

In [5]:
import pandas as pd

# Convertir el resultado del query en un DataFrame
columns = [desc[0] for desc in cursor.description]  # Obtener los nombres de las columnas
df_result = pd.DataFrame(result, columns=columns)

# Mostrar el DataFramE
df_result

,BF5BBFI1221BI_B2129FIJF,BF5BBFI1221BI_F5997JB9F,BF5BBFI1221BI_Y7FY7YF1B,-- Clave\nCOUNT(BF5BBFI1221BI_Y7FY7YF1B)
0,Broncoscopia fibroóptica,D,3322,275
1,Otra broncoscopia,D,3323,162
2,Drenaje de cavidad pleural por toracoscopía,Q,3406,135
3,Otra septoplastia,Q,2188,126
4,Laringoscopia y otra traqueoscopia,D,3142,122
...,...,...,...,...
363,Pericardiocentesis,None,370,1
364,Otras operaciones sobre hígado,None,509,1
365,Biopsia cerrada [endoscópica] de tráquea,D,3144,1
366,"Otra inmovilización, presión y cuidado de herida",T,9359,1
367,Otra endoscopía de intestino delgado,D,4513,1

In [6]:
# Renombrar las columnas del DataFrame
df_result.rename(columns={
    'BF5BBFI1221BI_B2129FIJF': 'Descripción',
    'BF5BBFI1221BI_F5997JB9F': 'Tipo',
    'BF5BBFI1221BI_Y7FY7YF1B': 'Clave',
    '-- Clave\nCOUNT(BF5BBFI1221BI_Y7FY7YF1B)': 'Conteo por Clave'
}, inplace=True)

# Mostrar el DataFrame con los nuevos nombres de columnas
df_result

,Descripción,Tipo,Clave,Conteo por Clave
0,Broncoscopia fibroóptica,D,3322,275
1,Otra broncoscopia,D,3323,162
2,Drenaje de cavidad pleural por toracoscopía,Q,3406,135
3,Otra septoplastia,Q,2188,126
4,Laringoscopia y otra traqueoscopia,D,3142,122
...,...,...,...,...
363,Pericardiocentesis,None,370,1
364,Otras operaciones sobre hígado,None,509,1
365,Biopsia cerrada [endoscópica] de tráquea,D,3144,1
366,"Otra inmovilización, presión y cuidado de herida",T,9359,1
367,Otra endoscopía de intestino delgado,D,4513,1